### PR TITLE
DB/Messaging integration improved

### PR DESCRIPTION
**Pull request by LeonArcher**
blablabla

### CODE REVIEW

**Comment by K-Mike** [comment]
lgtm

**Comment by cypt** [comment]
lgtm

**Comment by cypt** [comment]
approvals/lgtm

**Comment by LeonArcher** [comment]
lgtm

**Comment by LeonArcher** [comment]
approvals/lgtm

**Comment by K-Mike** [comment]
approvals/lgtm

**Comment by cypt** [comment]
lgtm

**Pull request closed without merging**
